# Generated by Django 4.2.7 on 2023-11-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0003_remove_category_subscribers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribers',
            new_name='user',
        ),
    ]
