# Generated by Django 4.2.7 on 2023-11-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0005_categorysubscriber_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorysubscriber',
            old_name='subscriber',
            new_name='subscribers',
        ),
    ]
